# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bc6330b6dad00eb4a8f3d379517fb07a99a1fd5c9c357f33350e6644e485c69c221e2648995cd1c065a07049b7e14d950cc09c9624a0ebf3c55c70d32537d6e0

test:
  secret_key_base: b316b602fd74f098990deaa081c7e9b1bf51a653920cdf2896aade2686e16d3679c67b7c2845a5c9517261d988237813c78a82165e67b7c5fc81082db6f578c0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
